spring:
  application:
    name: discovery-service
  profiles:
    active: development
    include: development

---
spring:
  profiles: development
server:
  port: ${vcap.application.port:8761}
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    status-page-url: https://${eureka.hostname}/info
    health-check-url: https://${eureka.hostname}/health
    prefer-ip-address: true
    home-page-url: https://${eureka.hostname}/
      
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/